SelectionKey=1234567890
PageSize=10
CandidateLayout=Vertical
UseKeypadAsSelection=False
AddPhraseForward=True
ChoiceBackward=True
AutoShiftCursor=True
SpaceAsSelection=False
AsciiPunctuation=True
Layout="Hsu's Keyboard"
