[projects.'d:\ca\cases\2026\nexusdb']
trust_level = "trusted"

[projects.'d:\notes\workflow\envcross_dotfiles']
trust_level = "trusted"

[desktop]
integratedTerminalShell = "commandPrompt"
show-context-window-usage = true
browser-download-prompt-enabled = true
followUpQueueMode = "queue"

[desktop.open-in-target-preferences]
global = "zed"

[windows]
sandbox = "unelevated"
