ConfigFile = '/home/lou/.config/lazysql/config.toml'

[application]
default_page_size = 300
disable_sidebar = false
sidebar_overlay = false
max_query_history_per_connection = 100
tree_width = 30
json_viewer_word_wrap = false
enter_opens_json_viewer = false

[[database]]
Name = 'Personal_Info'
URL = '/home/lou/Documents/ai-memory/user.db'
Provider = 'sqlite3'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = ''
URLParams = ''
ReadOnly = false
Schemas = []
Commands = []

[[database]]
Name = 'Training'
URL = '/home/lou/Documents/ai-memory/trainer.db'
Provider = 'sqlite3'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = ''
URLParams = ''
ReadOnly = false
Schemas = []
Commands = []

[[database]]
Name = 'learning_events'
URL = '/home/lou/Documents/ai-memory/events.db'
Provider = 'sqlite3'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = ''
URLParams = ''
ReadOnly = false
Schemas = []
Commands = []

[[database]]
Name = 'Projects'
URL = '/home/lou/Documents/ai-memory/projects.db'
Provider = 'sqlite3'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = ''
URLParams = ''
ReadOnly = false
Schemas = []
Commands = []

[[database]]
Name = 'Progress'
URL = '/home/lou/Documents/ai-memory/progress.db'
Provider = 'sqlite3'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = ''
URLParams = ''
ReadOnly = false
Schemas = []
Commands = []
